optimized

diff --git a/bin/ndk-pkg b/bin/ndk-pkg
--- a/bin/ndk-pkg
+++ b/bin/ndk-pkg
@@ -6646,33 +6646,41 @@ __adjust_elf_files_for_the_given_target() {
                     continue
                 fi
 
+                unset FILEMAGIC
+                FILEMAGIC="$(hexdump -n 20 -v -e '1/1 "%02X" ""' "$FILEPATH")"
+
                 # http://www.sco.com/developers/gabi/latest/ch4.eheader.html
-                unset ELF_HEADER_HEX
-                ELF_HEADER_HEX="$(hexdump -n 20 -v -e '1/1 "%02X" ""' "$FILEPATH")"
+                case $FILEMAGIC in
+                    7F454C46*)
+                        {
+                            case $y in
+                                *.o)
+                                    case $TARGET_OS_ABI in
+                                        armeabi-v7a) [ "$FILEMAGIC" = '7F454C4601010100000000000000000001002800' ] ;;
+                                        arm64-v8a)   [ "$FILEMAGIC" = '7F454C460201010000000000000000000100B700' ] ;;
+                                        x86)         [ "$FILEMAGIC" = '7F454C4601010100000000000000000001000300' ] ;;
+                                        x86_64)      [ "$FILEMAGIC" = '7F454C4602010100000000000000000001003E00' ] ;;
+                                    esac
+                                    ;;
+                                *)  case $TARGET_OS_ABI in
+                                        armeabi-v7a) [ "$FILEMAGIC" = '7F454C4601010100000000000000000003002800' ] ;;
+                                        arm64-v8a)   [ "$FILEMAGIC" = '7F454C460201010000000000000000000300B700' ] ;;
+                                        x86)         [ "$FILEMAGIC" = '7F454C4601010100000000000000000003000300' ] ;;
+                                        x86_64)      [ "$FILEMAGIC" = '7F454C4602010100000000000000000003003E00' ] ;;
+                                    esac
+                            esac
+                        } || die "invalid elf file: $FILEPATH. elf header mismatch."
 
-                if [ "$(printf '%s\n' "$ELF_HEADER_HEX" | cut -c1-8)" = '7F454C46' ] ; then
-                    unset ELF_HEADER_HEX_e_machine
-                    ELF_HEADER_HEX_e_machine="$(printf '%s\n' "$ELF_HEADER_HEX" | cut -c37-38)"
-
-                    {
-                        case $TARGET_OS_ABI in
-                            armeabi-v7a) [ "$ELF_HEADER_HEX_e_machine" = '28' ] ;;
-                            arm64-v8a)   [ "$ELF_HEADER_HEX_e_machine" = 'B7' ] ;;
-                            x86)         [ "$ELF_HEADER_HEX_e_machine" = '03' ] ;;
-                            x86_64)      [ "$ELF_HEADER_HEX_e_machine" = '3E' ] ;;
-                        esac
-                    } || die "invalid elf file: $FILEPATH. arch mismatch."
-
-                    if [ "$x" = bin ] || [ "$x" = sbin ] ; then
-                        if ! "$READELF" -d "$FILEPATH" | grep FLAGS_1 | grep -q PIE ; then
-                            die "invalid elf file: $FILEPATH. It is not Position Independent Executable."
+                        if [ "$x" = bin ] || [ "$x" = sbin ] ; then
+                            if ! "$READELF" -d "$FILEPATH" | grep FLAGS_1 | grep -q PIE ; then
+                                die "invalid elf file: $FILEPATH. It is not Position Independent Executable."
+                            fi
                         fi
-                    fi
 
-                    if [ "$BUILD_TYPE" = release ] ; then
-                        run "$STRIP" $STRIP_ARGS "$FILEPATH" || true
-                    fi
-                fi
+                        if [ "$BUILD_TYPE" = release ] ; then
+                            run "$STRIP" $STRIP_ARGS "$FILEPATH" || true
+                        fi
+                esac
             done
         fi
     done
