optimized
Signed-off-by: leleliu008 <leleliu008@gmail.com>

diff --git a/ndk-pkg b/ndk-pkg
--- a/ndk-pkg
+++ b/ndk-pkg
@@ -5568,6 +5568,10 @@ $PACKAGE_BUILD0_ACTIONS
         TARGET_TRIPLE="$TARGET_OS_ARCH-linux-android"
     fi
 
+    export ANDROID_TARGET="${TARGET_TRIPLE}${TARGET_OS_VERS}"
+    export ANDROID_NDK_CC
+    export ANDROID_NDK_SYSROOT
+
     #########################################################################################
 
     step "locate C/C++ toolchain for target build"
@@ -5603,28 +5607,141 @@ $PACKAGE_BUILD0_ACTIONS
 #include <string.h>
 #include <unistd.h>
 
+#define ACTION_COMPILE 1
+#define ACTION_CREATE_SHARED_LIBRARY 2
+#define ACTION_CREATE_STATICALLY_LINKED_EXECUTABLE 3
+#define ACTION_CREATE_DYNAMICALLY_LINKED_EXECUTABLE 4
+
 int main(int argc, char * argv[]) {
-    const char * const PROXIED_CC = "$CC";
-
-    const char * const SYSROOT = "$SYSROOT";
-
-    size_t   sysrootLength = strlen(SYSROOT) + 11;
-    char     sysroot[sysrootLength];
-    snprintf(sysroot, sysrootLength, "--sysroot=%s", SYSROOT);
-
-    char * argv2[argc + 2];
-
-    argv2[0] = (char*)PROXIED_CC;
-    argv2[1] = sysroot;
+    const char * options[5] = { "-shared", "-static", "--static", "-pie", "-Wl,-Bdynamic" };
+          int    indexes[5] = {    -1,         -1,        -1,       -1,         -1        };
 
     for (int i = 1; i < argc; i++) {
-        argv2[i + 1] = argv[i];
+        for (int j = 0; j < 5; j++) {
+            if (strcmp(argv[i], options[j]) == 0) {
+                indexes[j] = i;
+            }
+
+            if ((indexes[0] > 0) && (indexes[1] > 0) && (indexes[2] > 0) && (indexes[3] > 0) && (indexes[4] > 0)) {
+                goto lable;
+            }
+        }
     }
 
-    argv2[argc + 1] = NULL;
+    lable:
+    // printf("      -shared = %d\n", indexes[0]);
+    // printf("      -static = %d\n", indexes[1]);
+    // printf("     --static = %d\n", indexes[2]);
+    // printf("-Wl,-Bdynamic = %d\n", indexes[3]);
+    // printf("         -pie = %d\n", indexes[4]);
 
-    execv (PROXIED_CC, argv2);
-    perror(PROXIED_CC);
+    int action = 0;
+
+    if (indexes[0] > 0) {
+        // if -shared option is specified, then remove -static , --static , -pie options if they also are specified
+        action = ACTION_CREATE_SHARED_LIBRARY;
+    } else if ((indexes[1] > 0) || (indexes[2] > 0)) {
+        // if -shared option is not specified, but -static or --static option is specified, then remove -pie , -Wl,-Bdynamic option if it also is specified
+        action = ACTION_CREATE_STATICALLY_LINKED_EXECUTABLE;
+    } else if (indexes[3] > 0) {
+        action = ACTION_CREATE_DYNAMICALLY_LINKED_EXECUTABLE;
+    }
+
+    /////////////////////////////////////////////////////////////////
+
+    char * const cc = getenv("ANDROID_NDK_CC");
+
+    if (cc == NULL) {
+        fprintf(stderr, "ANDROID_NDK_CC environment variable is not set.\n");
+        return 1;
+    }
+
+    if (cc[0] == '\0') {
+        fprintf(stderr, "ANDROID_NDK_CC environment variable value should be a non-empty string.\n");
+        return 2;
+    }
+
+    /////////////////////////////////////////////////////////////////
+
+    const char * const TARGET = getenv("ANDROID_TARGET");
+
+    if (TARGET == NULL) {
+        fprintf(stderr, "ANDROID_TARGET environment variable is not set.\n");
+        return 1;
+    }
+
+    if (TARGET[0] == '\0') {
+        fprintf(stderr, "ANDROID_TARGET environment variable value should be a non-empty string.\n");
+        return 2;
+    }
+
+    size_t   targetArgLength = strlen(TARGET) + 10;
+    char     targetArg[targetArgLength];
+    snprintf(targetArg, targetArgLength, "--target=%s", TARGET);
+
+    /////////////////////////////////////////////////////////////////
+
+    const char * const SYSROOT = getenv("ANDROID_NDK_SYSROOT");
+
+    if (SYSROOT == NULL) {
+        fprintf(stderr, "ANDROID_NDK_SYSROOT environment variable is not set.\n");
+        return 1;
+    }
+
+    if (SYSROOT[0] == '\0') {
+        fprintf(stderr, "ANDROID_NDK_SYSROOT environment variable value should be a non-empty string.\n");
+        return 2;
+    }
+
+    size_t   sysrootArgLength = strlen(SYSROOT) + 11;
+    char     sysrootArg[sysrootArgLength];
+    snprintf(sysrootArg, sysrootArgLength, "--sysroot=%s", SYSROOT);
+
+    /////////////////////////////////////////////////////////////////
+
+    char * argv2[argc + 3];
+
+    argv2[0] = cc;
+    argv2[1] = targetArg;
+    argv2[2] = sysrootArg;
+
+    if (action == ACTION_CREATE_SHARED_LIBRARY) {
+        for (int i = 1; i < argc; i++) {
+            if (strcmp(argv[i], "-static") == 0) {
+                argv2[i + 2] = (char*)"--shared";
+            } else if (strcmp(argv[i], "--static") == 0) {
+                argv2[i + 2] = (char*)"--shared";
+            } else if (strcmp(argv[i], "-pie") == 0) {
+                argv2[i + 2] = (char*)"--shared";
+            } else {
+                argv2[i + 2] = argv[i];
+            }
+        }
+    } else if (action == ACTION_CREATE_STATICALLY_LINKED_EXECUTABLE) {
+        for (int i = 1; i < argc; i++) {
+            if (strcmp(argv[i], "-Wl,-Bdynamic") == 0) {
+                argv2[i + 2] = (char*)"-static";
+            } else if (strcmp(argv[i], "-pie") == 0) {
+                argv2[i + 2] = (char*)"-static";
+            } else {
+                argv2[i + 2] = argv[i];
+            }
+        }
+    } else {
+        for (int i = 1; i < argc; i++) {
+            argv2[i + 2] = argv[i];
+        }
+    }
+
+    argv2[argc + 2] = NULL;
+
+    for (int i = 0; argv2[i] != NULL; i++) {
+        printf("%s ", argv2[i]);
+    }
+    printf("\n");
+
+    execv (cc, argv2);
+    perror(cc);
     return -1;
 }
 EOF
@@ -5643,28 +5760,123 @@ EOF
 #include <string.h>
 #include <unistd.h>
 
+#define ACTION_COMPILE 1
+#define ACTION_CREATE_SHARED_LIBRARY 2
+#define ACTION_CREATE_STATICALLY_LINKED_EXECUTABLE 3
+#define ACTION_CREATE_DYNAMICALLY_LINKED_EXECUTABLE 4
+
 int main(int argc, char * argv[]) {
-    const char * const PROXIED_CXX = "$CXX";
-
-    const char * const SYSROOT = "$SYSROOT";
-
-    size_t   sysrootLength = strlen(SYSROOT) + 11;
-    char     sysroot[sysrootLength];
-    snprintf(sysroot, sysrootLength, "--sysroot=%s", SYSROOT);
-
-    char * argv2[argc + 2];
-
-    argv2[0] = (char*)PROXIED_CXX;
-    argv2[1] = sysroot;
+    const char * options[5] = { "-shared", "-static", "--static", "-pie", "-Wl,-Bdynamic" };
+          int    indexes[5] = {    -1,         -1,        -1,       -1,         -1        };
 
     for (int i = 1; i < argc; i++) {
-        argv2[i + 1] = argv[i];
+        for (int j = 0; j < 5; j++) {
+            if (strcmp(argv[i], options[j]) == 0) {
+                indexes[j] = i;
+            }
+
+            if ((indexes[0] > 0) && (indexes[1] > 0) && (indexes[2] > 0) && (indexes[3] > 0) && (indexes[4] > 0)) {
+                goto lable;
+            }
+        }
     }
 
-    argv2[argc + 1] = NULL;
+    lable:
+    // printf("      -shared = %d\n", indexes[0]);
+    // printf("      -static = %d\n", indexes[1]);
+    // printf("     --static = %d\n", indexes[2]);
+    // printf("-Wl,-Bdynamic = %d\n", indexes[3]);
+    // printf("         -pie = %d\n", indexes[4]);
 
-    execv (PROXIED_CXX, argv2);
-    perror(PROXIED_CXX);
+    int action = 0;
+
+    if (indexes[0] > 0) {
+        // if -shared option is specified, then remove -static , --static , -pie options if they also are specified
+        action = ACTION_CREATE_SHARED_LIBRARY;
+    } else if ((indexes[1] > 0) || (indexes[2] > 0)) {
+        // if -shared option is not specified, but -static or --static option is specified, then remove -pie , -Wl,-Bdynamic option if it also is specified
+        action = ACTION_CREATE_STATICALLY_LINKED_EXECUTABLE;
+    } else if (indexes[3] > 0) {
+        action = ACTION_CREATE_DYNAMICALLY_LINKED_EXECUTABLE;
+    }
+
+    /////////////////////////////////////////////////////////////////
+
+    char * const cxx = getenv("ANDROID_NDK_CXX");
+
+    if (cxx == NULL) {
+        fprintf(stderr, "ANDROID_NDK_CXX environment variable is not set.\n");
+        return 1;
+    }
+
+    if (cxx[0] == '\0') {
+        fprintf(stderr, "ANDROID_NDK_CXX environment variable value should be a non-empty string.\n");
+        return 2;
+    }
+
+    /////////////////////////////////////////////////////////////////
+
+    const char * const TARGET = getenv("ANDROID_TARGET");
+
+    size_t   targetArgLength = strlen(TARGET) + 10;
+    char     targetArg[targetArgLength];
+    snprintf(targetArg, targetArgLength, "--target=%s", TARGET);
+
+    /////////////////////////////////////////////////////////////////
+
+    const char * const SYSROOT = getenv("ANDROID_NDK_SYSROOT");
+
+    size_t   sysrootArgLength = strlen(SYSROOT) + 11;
+    char     sysrootArg[sysrootArgLength];
+    snprintf(sysrootArg, sysrootArgLength, "--sysroot=%s", SYSROOT);
+
+    /////////////////////////////////////////////////////////////////
+
+    char * argv2[argc + 3];
+
+    argv2[0] = cxx;
+    argv2[1] = targetArg;
+    argv2[2] = sysrootArg;
+
+    if (action == ACTION_CREATE_SHARED_LIBRARY) {
+    // if -shared option is passed, then remove -static , --static , -pie options if they also are passed
+        for (int i = 1; i < argc; i++) {
+            if (strcmp(argv[i], "-static") == 0) {
+                argv2[i + 2] = (char*)"--shared";
+            } else if (strcmp(argv[i], "--static") == 0) {
+                argv2[i + 2] = (char*)"--shared";
+            } else if (strcmp(argv[i], "-pie") == 0) {
+                argv2[i + 2] = (char*)"--shared";
+            } else {
+                argv2[i + 2] = argv[i];
+            }
+        }
+    } else if (action == ACTION_CREATE_STATICALLY_LINKED_EXECUTABLE) {
+    // if -shared option is not passed, but -static or --static option is passed, then remove -pie , -Wl,-Bdynamic option if it also is passed
+        for (int i = 1; i < argc; i++) {
+            if (strcmp(argv[i], "-Wl,-Bdynamic") == 0) {
+                argv2[i + 2] = (char*)"-static";
+            } else if (strcmp(argv[i], "-pie") == 0) {
+                argv2[i + 2] = (char*)"-static";
+            } else {
+                argv2[i + 2] = argv[i];
+            }
+        }
+    } else {
+        for (int i = 1; i < argc; i++) {
+            argv2[i + 2] = argv[i];
+        }
+    }
+
+    argv2[argc + 2] = NULL;
+
+    for (int i = 0; argv2[i] != NULL; i++) {
+        printf("%s ", argv2[i]);
+    }
+    printf("\n");
+
+    execv (cxx, argv2);
+    perror(cxx);
     return -1;
 }
 EOF
@@ -6973,23 +7185,28 @@ __adjust_elf_files_for_the_given_target() {
                     abort 1 "ELF file header mismatch: $FILEPATH\n    expect : $FILE_HEADER_EXPACT\n    actual : $FILE_HEADER_ACTUAL"
                 fi
 
+                # may report: patchelf: cannot find section '.interp'. The input file is most likely statically linked
                 PT_INTERP=
-                PT_INTERP="$(patchelf --print-interpreter "$FILEPATH")"
+                PT_INTERP="$(patchelf --print-interpreter "$FILEPATH" 2>/dev/null || true)"
 
                 if [ -n  "$PT_INTERP" ] ; then
                     if [ "$PT_INTERP" != "$ANDROID_DYNAMIC_LINKER_PATH" ] ; then
                         abort 1 "ELF file PT_INTERP mismatch: $FILEPATH\n    expect : $ANDROID_DYNAMIC_LINKER_PATH\n    actual : $PT_INTERP"
+                    fi
+
+                    # shared library do not have .interp section usually.
+                    # dynamically linked executable have the .interp section usually.
+                    #
+                    # https://source.android.com/security/enhancements/enhancements50
+                    # Android 5.0 and later only support position-independent executables (-fPIE)
+                    if ! "$READELF" -d "$FILEPATH" | grep FLAGS_1 | grep -q PIE ; then
+                        abort 1 "invalid ELF file: $FILEPATH. Android 5.0 and later requires dynamically linked executable to support PIE (position-independent executables)."
                     fi
                 fi
 
                 if basename "$FILEPATH" | grep -q '^lib.*\.so' ; then
                     :
                 else
-                    # https://source.android.com/security/enhancements/enhancements50
-                    # Android 5.0 and later only support position-independent executables (-fPIE)
-                    if ! "$READELF" -d "$FILEPATH" | grep FLAGS_1 | grep -q PIE ; then
-                        abort 1 "invalid ELF file: $FILEPATH. Android 5.0 and later requires dynamically linked executable to support PIE (position-independent executables)."
-                    fi
 
                     if [ "$BUILD_TYPE" = release ] ; then
                         run "$STRIP" $STRIP_ARG "$FILEPATH" || true
